# Generated by Django 5.2.4 on 2025-07-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovefi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currency',
            new_name='currency_code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency',
            new_name='currency_code',
        ),
    ]
