# Generated by Django 5.2.4 on 2025-07-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovefi', '0002_rename_currency_account_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency_code',
        ),
    ]
