# Generated by Django 5.2.4 on 2025-07-28 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovefi', '0004_country_currency_transactioncategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country_code',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lovefi.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lovefi.country'),
            preserve_default=False,
        ),
    ]
